INSERT INTO APP.ROL (ROL) VALUES(0);
INSERT INTO APP.ROL (ROL) VALUES(1);
INSERT INTO APP.ROL (ROL) VALUES(2);
INSERT INTO APP.ROL (ROL) VALUES(3);

--INSERT INTO APP.HISTORIAL (CUENTA_ALIAS, ID_ID) VALUES();  --falta por rellenar

--[Castores, Lobatos, Scouts, Escultas, Rovers, Scouters de Apoyo]
INSERT INTO APP.GRUPO (ID, NOMBRE) VALUES(0,'Castores');
INSERT INTO APP.GRUPO (ID, NOMBRE) VALUES(1,'Lobatos');
INSERT INTO APP.GRUPO (ID, NOMBRE) VALUES(2,'Scouts');
INSERT INTO APP.GRUPO (ID, NOMBRE) VALUES(3,'Escultas');
INSERT INTO APP.GRUPO (ID, NOMBRE) VALUES(4,'Rovers');
INSERT INTO APP.GRUPO (ID, NOMBRE) VALUES(5,'Scouter de Apoyo');

INSERT INTO APP.LOCALIDAD (CODIGO_POSTAL, NOMBRE, PROVINCIA) VALUES(29010, 'malaga', 'malaga');

INSERT INTO APP.EVENTO (ID, DESCRIPCION, FECHA, NOMBRE) VALUES(100, 'EVENTO1', '2018-06-02', 'EVENTO1');
INSERT INTO APP.EVENTO (ID, DESCRIPCION, FECHA, NOMBRE) VALUES(101, 'EVENTO2', '2018-06-02', 'EVENTO2');
INSERT INTO APP.EVENTO (ID, DESCRIPCION, FECHA, NOMBRE) VALUES(102, 'EVENTO3', '2018-06-02', 'EVENTO3');
INSERT INTO APP.EVENTO (ID, DESCRIPCION, FECHA, NOMBRE) VALUES(103, 'EVENTO4', '2018-06-02', 'EVENTO4');
INSERT INTO APP.EVENTO (ID, DESCRIPCION, FECHA, NOMBRE) VALUES(104, 'EVENTO5', '2018-06-02', 'EVENTO5');
--TUTOR LEGAL
INSERT INTO APP.TUTOR_LEGAL(DNI, APELLIDO,  NOMBRE) VALUES ('123456' , 'MARQUEZ DOMINGO' , 'PEPE');
INSERT INTO APP.TUTOR_LEGAL(DNI, APELLIDO,  NOMBRE) VALUES ('3456789' , 'FERNANDEZ' , 'PABLO');
INSERT INTO APP.TUTOR_LEGAL (DNI, APELLIDO,  NOMBRE) VALUES ('987654', 'MUÑOZ' , 'MARIA');

INSERT INTO APP.USUARIO ("ALIAS", APELLIDOS, "CONTRASEÑA", CREDENCIAL,
  DIRECCION, DNI, EMAIL, FECHA_BAJA, 
  FECHA_INGRESO, FECHA_NACIMIENTO, NOMBRE, TELEFONO, 
  GRUPO_ID, RESIDE_EN_CODIGO_POSTAL, ROL_ROL) 
 VALUES ('educando1', 'u1', '1111', 0,
   NULL, '111111111', 'u1', NULL, 
   '2018-06-02', '2018-06-02', 'u1', '999999999',
    0, 29010, 0);

INSERT INTO APP.USUARIO ("ALIAS", APELLIDOS, "CONTRASEÑA", CREDENCIAL,
  DIRECCION, DNI, EMAIL, FECHA_BAJA, 
  FECHA_INGRESO, FECHA_NACIMIENTO, NOMBRE, TELEFONO, 
  GRUPO_ID, RESIDE_EN_CODIGO_POSTAL, ROL_ROL) 
 VALUES ('scouter1', 'u2', '1111', 1,
   NULL, '111111112', 'u2', NULL, 
   '2018-06-02', '2018-06-02', 'u2', '666666666',
    0, 29010, 1);

 INSERT INTO APP.USUARIO ("ALIAS", APELLIDOS, "CONTRASEÑA", CREDENCIAL,
  DIRECCION, DNI, EMAIL, FECHA_BAJA, 
  FECHA_INGRESO, FECHA_NACIMIENTO, NOMBRE, TELEFONO, 
  GRUPO_ID, RESIDE_EN_CODIGO_POSTAL, ROL_ROL) 
 VALUES ('coordinador1', 'u2', '1111', 1,
   NULL, '111111112', 'u2', null, 
   '2018-06-02', '2018-06-02', 'u2', NULL,
    0, 29010, 2);

INSERT INTO APP.JND_EVN_GRP (EVENTO_FK, GRUPO_FK) 
 VALUES (103, 0);
INSERT INTO APP.DOCUMENTO (ID, ESTADO_DOCUMENTO, FECHA_LIMITE, FECHA_SUBIDA, "FILE", FILENAME, NOMBRE, "DUEÑO_ALIAS") 
 VALUES (0, 1, '2018-06-03', NULL, NULL, NULL, 'e1', 'educando1');
